name: Install and Run Chromium-Gost with Selenium

on:
  push:
    branches:
      - main

jobs:
  run-chromium-gost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files in root directory
        run: |
          ls -la

      - name: List files in bin directory
        run: |
          ls -la bin
          

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb
          pip3 install webdriver-manager
          


      - name: Verify installation
        run: |
          which chromium-browser
          chromium-browser --version


      - name: Install Selenium
        run: |
          pip3 install selenium

     


      - name: Run Selenium Test
        run: |
          python3 test/autorization.py
