name: Install and Run Chromium-Gost with Selenium

on:
  push:
    branches:
      - main

jobs:
  run-chromium-gost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files in root directory
        run: |
          ls -la

      - name: List files in bin directory
        run: |
          ls -la bin

      - name: Extract and Install CryptoPro CSP
        run: |
          cd ./bin
          tar -xzf linux-amd64_deb.tgz
          cd linux-amd64_deb
          sudo bash install.sh

      - name: Install and extract plugin
        run: |
            sudo mkdir -p /opt/chromium-gost/plugin
            sudo tar -xvf ./bin/cades-linux-amd64.tar -C /opt/chromium-gost/plugin/
            sudo chmod -R 755 /opt/chromium-gost/plugin/

            # Установите необходимые пакеты CryptoPro CSP
            sudo apt-get update
            sudo apt-get install -y lsb-cprocsp-base lsb-cprocsp-rdr-64 lsb-cprocsp-kc1-64 lsb-cprocsp-capilite-64 cprocsp-curl-64 lsb-cprocsp-ca-certs

            # Установите rdr_gui_gtk пакет вручную
            if [ -f ./bin/cprocsp-rdr-gui-gtk-64_*.deb ]; then
              sudo dpkg -i ./bin/cprocsp-rdr-gui-gtk-64_*.deb
              sudo apt-get install -f -y
            else
              echo "Package cprocsp-rdr-gui-gtk-64_*.deb not found."
              exit 1
            fi

            # Установите .deb файлы
            sudo dpkg -i /opt/chromium-gost/plugin/cades-linux-amd64/*.deb
            sudo apt-get install -f -y

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb python3-pip ./bin/chromium-gost-126.0.6478.126-linux-amd64.deb
          pip3 install webdriver-manager


      - name: Verify installation
        run: |
          which chromium-browser
          chromium-browser --version

      - name: Run Chromium-Gost
        run: |
          nohup chromium-browser &

      - name: Install Selenium
        run: |
          pip3 install selenium

      - name: Set up Xvfb
        run: |
         sudo apt-get install -y xvfb
         Xvfb :99 -screen 0 1920x1080 &
         export DISPLAY=:99

      - name: Run Selenium Test
        run: |
          python3 test/autorization.py
